In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Audio
sound_file = 'https://www.soundjay.com/button/beep-01a.wav'

In [3]:
data = pd.read_csv('train.csv')
data.head(n=3)

,customer_ID,shopping_pt,record_type,day,time,state,location,group_size,homeowner,car_age,...,C_previous,duration_previous,A,B,C,D,E,F,G,cost
0,10000000,1,0,0,08:35,IN,10001,2,0,2,...,1.0,2.0,1,0,2,2,1,2,2,633
1,10000000,2,0,0,08:38,IN,10001,2,0,2,...,1.0,2.0,1,0,2,2,1,2,1,630
2,10000000,3,0,0,08:38,IN,10001,2,0,2,...,1.0,2.0,1,0,2,2,1,2,1,630

In [6]:
id_grouped = data.groupby('customer_ID')

In [7]:
id_max_idx = id_grouped.shopping_pt.idxmax()
Audio(url=sound_file, autoplay=True)

In [8]:
data_max_shopping_pt = data.iloc[id_max_idx]

In [9]:
np.unique(data_max_shopping_pt.columns)

array(['A', 'B', 'C', 'C_previous', 'D', 'E', 'F', 'G', 'age_oldest',
       'age_youngest', 'car_age', 'car_value', 'cost', 'customer_ID',
       'day', 'duration_previous', 'group_size', 'homeowner', 'location',
       'married_couple', 'record_type', 'risk_factor', 'shopping_pt',
       'state', 'time'], dtype=object)

In [10]:
def char_range(c1, c2):
    """Generates the characters from `c1` to `c2`, inclusive."""
    for c in xrange(ord(c1), ord(c2)+1):
        yield chr(c)

In [11]:
df_list = []
for index, row in data_max_shopping_pt.iterrows():
    df_row = {}
    df_row['customer_ID'] = `int(row.customer_ID)`
    plan = ''.join([`int(row[char])` for char in char_range('A', 'G')])
    df_row['plan'] = plan
    #print df_row
    df_list.append(df_row)
    #print df_list
df = pd.DataFrame(df_list)

In [14]:
df.to_csv('prediction.csv', index=False)

In [12]:
Audio(url=sound_file, autoplay=True)

In [19]:
data_max_shopping_pt.set_index('customer_ID')

,shopping_pt,record_type,day,time,state,location,group_size,homeowner,car_age,car_value,...,C_previous,duration_previous,A,B,C,D,E,F,G,cost
customer_ID,,,,,,,,,,,,,,,,,,,,,
10000000,9,1,0,12:07,IN,10001,2,0,2,g,...,1.0,2.0,1,0,2,2,1,2,1,634
10000005,6,1,3,09:09,NY,10006,1,0,10,e,...,3.0,13.0,0,0,3,2,0,0,2,731
10000007,8,1,4,14:26,PA,10008,1,0,11,c,...,2.0,4.0,0,0,1,2,0,0,1,602
10000013,4,1,4,09:31,WV,10014,2,1,3,d,...,3.0,3.0,1,1,3,2,1,1,3,626
10000014,6,1,1,17:50,MO,10015,1,0,5,d,...,1.0,2.0,1,1,1,1,0,2,2,614
10000016,10,1,3,13:15,OH,10018,1,0,6,d,...,3.0,9.0,2,0,3,3,0,3,3,597
10000019,8,1,1,11:34,OK,10021,1,0,7,d,...,2.0,4.0,2,1,2,3,1,2,3,705
10000023,7,1,1,14:32,PA,10025,1,1,2,f,...,1.0,13.0,1,1,1,3,1,1,2,607
10000025,7,1,0,15:26,OH,10027,2,1,15,d,...,3.0,0.0,0,0,1,1,0,0,3,604
10000026,4,1,3,15:24,OH,10028,2,1,5,d,...,3.0,1.0,1,1,3,3,1,2,3,578
10000027,6,1,2,08:03,IN,10029,1,0,17,e,...,2.0,1.0,0,0,2,2,0,0,1,605
10000028,6,1,6,11:44,FL,10030,2,1,1,d,...,1.0,2.0,1,0,1,3,0,2,3,703
10000031,8,1,4,19:09,OR,10033,1,0,15,e,...,2.0,8.0,1,1,1,1,0,1,2,665
10000032,7,1,1,18:37,OR,10034,1,0,12,e,...,4.0,14.0,1,1,3,3,0,2,3,606
10000033,7,1,0,18:31,WA,10035,1,1,8,d,...,1.0,5.0,2,0,1,1,0,1,2,603
10000034,7,1,2,09:40,OK,10036,1,1,8,g,...,3.0,3.0,2,1,2,3,0,2,2,600
10000036,11,1,0,13:56,FL,10038,2,1,26,c,...,3.0,15.0,1,1,3,3,0,2,3,577
10000037,6,1,1,13:07,PA,10039,2,1,1,g,...,1.0,5.0,1,0,1,2,1,2,2,694
10000038,7,1,2,16:00,WA,10040,1,0,7,d,...,1.0,0.0,1,1,1,1,1,2,2,654
10000039,9,1,2,13:39,OH,10041,1,1,4,f,...,2.0,4.0,1,1,3,3,1,2,3,646
10000040,4,1,4,14:41,KS,10042,1,1,6,e,...,3.0,5.0,1,1,3,3,1,2,1,627
10000041,8,1,0,08:45,PA,10043,1,1,14,d,...,1.0,4.0,0,1,1,1,0,0,3,563
10000042,4,1,0,11:14,FL,10044,3,0,9,e,...,3.0,15.0,1,1,3,3,1,1,3,701
10000043,7,1,2,10:47,NY,10045,1,1,3,f,...,3.0,4.0,1,0,3,3,0,0,2,598
10000047,8,1,0,14:32,OH,10049,1,1,6,e,...,4.0,6.0,1,0,3,3,1,1,3,598
10000048,9,1,0,13:23,OH,10050,1,1,10,h,...,1.0,1.0,0,0,1,1,0,0,3,562
10000049,10,1,3,13:56,NV,10051,1,0,17,c,...,3.0,7.0,0,1,1,1,0,0,2,617
10000052,8,1,0,18:25,ID,10053,1,1,8,d,...,3.0,3.0,2,1,3,3,1,3,3,604
10000054,3,1,2,09:05,FL,10055,2,1,7,f,...,1.0,3.0,1,1,1,2,1,2,3,614
10000055,7,1,4,17:58,CO,10056,1,1,9,e,...,4.0,15.0,2,1,4,3,0,1,2,634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10152682,4,1,4,15:01,NY,11140,1,0,3,e,...,4.0,9.0,1,1,3,3,1,0,2,635
10152685,8,1,4,12:37,NY,14789,1,0,12,d,...,3.0,11.0,1,1,3,3,0,0,2,655
10152687,9,1,4,13:00,KY,14631,1,1,10,f,...,2.0,4.0,1,0,2,3,0,2,3,677
10152688,5,1,0,08:40,NY,12229,1,1,6,g,...,4.0,15.0,1,0,4,3,0,0,3,622
10152689,8,1,4,16:26,OH,10601,2,0,6,d,...,2.0,15.0,1,0,1,2,0,2,3,631
10152690,11,1,4,12:16,WA,13664,1,0,11,d,...,1.0,15.0,1,1,1,1,1,1,2,633
10152691,8,1,4,11:44,NY,15100,3,1,8,e,...,2.0,7.0,0,0,2,3,0,0,2,773
10152692,4,1,0,10:28,FL,11356,1,1,9,e,...,3.0,7.0,1,1,3,3,1,1,4,585
10152693,10,1,3,15:27,NY,10390,2,1,1,g,...,1.0,1.0,1,0,3,3,1,0,2,642
10152694,5,1,2,14:30,TN,10827,1,1,2,g,...,3.0,4.0,1,1,3,3,1,1,1,608
10152697,8,1,4,14:02,NM,15049,1,1,6,h,...,3.0,5.0,2,1,2,2,1,2,3,665
10152698,8,1,0,16:00,NY,11641,1,0,8,d,...,2.0,9.0,1,1,1,1,1,0,2,709
10152699,7,1,4,11:38,PA,10011,3,1,1,f,...,3.0,1.0,1,0,3,3,1,1,3,651
10152701,10,1,2,13:11,MS,10428,1,0,12,f,...,1.0,0.0,1,1,1,1,1,2,1,664
10152702,8,1,3,15:34,FL,11337,1,1,2,g,...,4.0,1.0,1,1,4,3,0,2,4,592
10152703,9,1,4,13:49,CT,14448,3,1,1,f,...,4.0,4.0,1,0,4,3,1,0,2,646
10152704,4,1,1,13:18,NH,10709,2,1,23,e,...,3.0,15.0,0,0,3,3,0,0,2,500
10152706,6,1,2,12:55,AL,10476,2,1,14,f,...,3.0,2.0,0,0,2,2,0,0,1,632
10152707,6,1,1,12:42,UT,13155,3,1,15,d,...,2.0,10.0,0,1,2,2,0,0,2,629
10152709,6,1,3,16:22,IN,11504,2,0,2,g,...,2.0,2.0,1,1,3,3,1,2,3,651
10152710,10,1,3,15:57,OH,12597,1,0,9,f,...,3.0,2.0,0,0,3,3,0,1,3,603
10152711,5,1,4,19:11,NV,11995,1,1,8,d,...,3.0,12.0,1,1,3,3,1,1,2,669
10152713,9,1,2,09:23,FL,11722,1,1,7,d,...,1.0,15.0,1,0,1,3,1,1,3,663
10152716,5,1,0,13:03,PA,10841,1,0,2,e,...,3.0,6.0,1,1,3,3,0,2,2,666
10152717,7,1,2,09:24,MD,10441,1,1,1,e,...,3.0,4.0,1,1,3,2,1,2,1,674
10152718,9,1,2,10:36,FL,11018,2,1,1,e,...,4.0,15.0,1,1,4,3,1,2,4,628
10152720,8,1,4,08:34,FL,14100,1,0,13,g,...,1.0,8.0,1,0,1,2,0,2,3,681
10152721,6,1,4,10:14,CT,11888,1,0,8,e,...,4.0,5.0,1,0,3,3,1,0,2,716
10152723,3,1,1,10:30,FL,10711,1,1,0,g,...,3.0,7.0,1,0,3,3,1,2,3,651
10152724,6,1,1,15:14,KY,10204,1,1,1,d,...,4.0,4.0,1,0,3,3,0,2,2,681

In [5]:
df=pd.DataFrame({ 'id':[1,1,1,1,2,2,2,2],
                   'a':range(8), 'b':range(8,0,-1) })

In [6]:
df

   a  b  id
0  0  8   1
1  1  7   1
2  2  6   1
3  3  5   1
4  4  4   2
5  5  3   2
6  6  2   2
7  7  1   2

In [7]:
df_max = df.groupby('id').idxmax()